"""Stable user-facing configuration contracts."""

from .radii import (
    INTERACTION_RADIUS_CONFIG_SCHEMA_VERSION,
    INTERACTION_RADIUS_CONVENTION_VERSION,
    INTERACTION_RADIUS_LENGTH_UNIT,
    DerivedInteractionRadii,
    InteractionRadiusConfig,
    RadiusConfigError,
    derive_interaction_radii,
    transport_support_config_from_radii,
    validate_radius_artifact_compatibility,
    validate_radius_model_compatibility,
)
from .training_run import (
    TRAINING_RUN_CONFIG_SCHEMA_VERSION,
    TRAINING_RUN_CONFIG_SCHEMA_VERSION_V1,
    TRAINING_RUN_CONFIG_SCHEMA_VERSION_V2,
    SUPPORTED_TRAINING_RUN_CONFIG_SCHEMA_VERSIONS,
    ResolvedScratchTrainingRun,
    ResolvedTrainingRun,
    TrainingDataConfig,
    TrainingDataSourceConfig,
    TrainingRunConfigOverrides,
    TrainingRuntimeConfig,
    TrainingRunConfig,
    TrainingRunConfigError,
    apply_training_run_overrides,
    load_effective_training_run_config,
    load_training_run_config,
    resolve_training_run,
    validate_training_run_config,
)
from .model_source import (
    BundleModelSourceConfig,
    ModelSourceConfig,
    ModelSourceConfigError,
    ScratchModelSourceConfig,
    ScratchReferenceTemplateSourceConfig,
)

__all__ = [
    "INTERACTION_RADIUS_CONFIG_SCHEMA_VERSION",
    "INTERACTION_RADIUS_CONVENTION_VERSION",
    "INTERACTION_RADIUS_LENGTH_UNIT",
    "TRAINING_RUN_CONFIG_SCHEMA_VERSION",
    "TRAINING_RUN_CONFIG_SCHEMA_VERSION_V1",
    "TRAINING_RUN_CONFIG_SCHEMA_VERSION_V2",
    "SUPPORTED_TRAINING_RUN_CONFIG_SCHEMA_VERSIONS",
    "BundleModelSourceConfig",
    "DerivedInteractionRadii",
    "InteractionRadiusConfig",
    "ModelSourceConfig",
    "ModelSourceConfigError",
    "RadiusConfigError",
    "ResolvedScratchTrainingRun",
    "ResolvedTrainingRun",
    "ScratchModelSourceConfig",
    "ScratchReferenceTemplateSourceConfig",
    "TrainingDataConfig",
    "TrainingDataSourceConfig",
    "TrainingRuntimeConfig",
    "TrainingRunConfig",
    "TrainingRunConfigOverrides",
    "TrainingRunConfigError",
    "derive_interaction_radii",
    "apply_training_run_overrides",
    "load_effective_training_run_config",
    "load_training_run_config",
    "resolve_training_run",
    "transport_support_config_from_radii",
    "validate_radius_artifact_compatibility",
    "validate_radius_model_compatibility",
    "validate_training_run_config",
]
