"""Dense balanced aggregate-vacancy entropic transport."""

from .batch import solve_ragged_atom_vacancy_ot
from .cost import (
    MICImageDiagnostics,
    atom_site_cost,
    atom_site_displacements,
    minimum_image_diagnostics,
    minimum_image_displacement,
)
from .factory import EVAL_ADAPTIVE, TRAIN_FIXED, solve_atom_vacancy_ot
from .edge_list import (
    CompactTransportEdges,
    build_compact_transport_edges,
    materialize_dense_plan,
)
from .result import (
    DensePlanMaterialization,
    DualVariables,
    EvalOTConfig,
    OTResult,
    SparseAdaptiveDiagnostics,
    SparseLineSearchDiagnostics,
    SparseNewtonOutcome,
    SparseOTResult,
    SparsePCGDiagnostics,
    SparsePCGOutcome,
    TrainSinkhornConfig,
)
from .sparse_adaptive import (
    SparseAdaptiveTransportError,
    solve_sparse_hybrid_eval,
    solve_sparse_newton_krylov,
    sparse_dual_objective,
    sparse_gauge_fixed_operator,
    sparse_jacobi_inverse,
    sparse_jacobian_vector_product,
    sparse_projected_pcg,
    sparse_residual_components,
    sparse_residual_vector,
    sparse_support_fingerprint,
)
from .sparse_sinkhorn import (
    sparse_fixed_sinkhorn_updates,
    sparse_marginal_residual_components,
    solve_sparse_sinkhorn_train_fixed,
    sparse_marginal_residuals,
    sparse_sinkhorn_full_update,
    sparse_transport_plan,
    sparse_zero_duals,
)
from .support import (
    TRANSPORT_SUPPORT_CONVENTION_VERSION,
    TransportSupportConfig,
    TransportSupportDiagnostics,
    TransportSupportError,
    compact_c2_switch,
)

__all__ = [
    "DualVariables",
    "DensePlanMaterialization",
    "CompactTransportEdges",
    "MICImageDiagnostics",
    "EVAL_ADAPTIVE",
    "EvalOTConfig",
    "OTResult",
    "SparseAdaptiveDiagnostics",
    "SparseAdaptiveTransportError",
    "SparseLineSearchDiagnostics",
    "SparseNewtonOutcome",
    "SparseOTResult",
    "SparsePCGDiagnostics",
    "SparsePCGOutcome",
    "TRAIN_FIXED",
    "TrainSinkhornConfig",
    "TRANSPORT_SUPPORT_CONVENTION_VERSION",
    "TransportSupportConfig",
    "TransportSupportDiagnostics",
    "TransportSupportError",
    "atom_site_cost",
    "atom_site_displacements",
    "build_compact_transport_edges",
    "compact_c2_switch",
    "minimum_image_diagnostics",
    "minimum_image_displacement",
    "materialize_dense_plan",
    "solve_atom_vacancy_ot",
    "solve_ragged_atom_vacancy_ot",
    "solve_sparse_sinkhorn_train_fixed",
    "solve_sparse_hybrid_eval",
    "solve_sparse_newton_krylov",
    "sparse_dual_objective",
    "sparse_fixed_sinkhorn_updates",
    "sparse_gauge_fixed_operator",
    "sparse_jacobi_inverse",
    "sparse_jacobian_vector_product",
    "sparse_marginal_residual_components",
    "sparse_marginal_residuals",
    "sparse_projected_pcg",
    "sparse_residual_components",
    "sparse_residual_vector",
    "sparse_sinkhorn_full_update",
    "sparse_support_fingerprint",
    "sparse_transport_plan",
    "sparse_zero_duals",
]
